In [3]:
import pandas as pd #Pandas library
import numpy as np # NumPy library
import sklearn
from sklearn.feature_extraction.text import TfidfTransformer
#from the module sklearn.feature_extraction.text import the class TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
#from the module sklearn.feature_extraction.text import the class CountVectorizer

In [1]:
corpus = ['The cats eat fish',
'Leo catches fish every day',
'Once a day I eat fish'
]

In [13]:
cv=CountVectorizer() #create the object cv to create an instance of the class CountVectorizer
word_count_vector=cv.fit_transform(corpus) # calculate word counts in corpus using the .fit_transform ( ) method
tokens = cv.get_feature_names() #return a list of feature names sorted by their indices using .get_feature_names_out ( ) method

In [14]:
print(word_count_vector.shape) #print the shape of the matrix (rows and columns)
print(tokens)
print(len(tokens))
print(word_count_vector.toarray()) #return an array method .toarray( )

(3, 9)
['catches', 'cats', 'day', 'eat', 'every', 'fish', 'leo', 'once', 'the']
9
[[0 1 0 1 0 1 0 0 1]
 [1 0 1 0 1 1 1 0 0]
 [0 0 1 1 0 1 0 1 0]]


In [15]:
doc_names = ['Doc{:d}'.format(index) for index, _ in enumerate(word_count_vector)]
#return the iterable object word_count_vector as an enumerate object with the enumerate() function
#for loop: iterate over the enumerate object word_count_vector
#format the specified values (index) and insert them inside the placeholder { }
#Doc = (doc0, doc1, doc2)
#{:d}: format code expecting integers (= word counts)

In [16]:
df = pd.DataFrame(data=word_count_vector.toarray(), index=doc_names, columns=tokens) # create the data frame
df

catches  cats  day  eat  every  fish  leo  once  the
Doc0        0     1    0    1      0     1    0     0    1
Doc1        1     0    1    0      1     1    1     0    0
Doc2        0     0    1    1      0     1    0     1    0

### Calculate term frequency

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
# from the module sklearn.feature_extraction.text import the class TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(use_idf=False, norm='l1')
# create the object tfidf_vectorizer to create an instance of the class TfidfVectorizer
#sum of absolute values of vector elements is 1
X = tfidf_vectorizer.fit_transform(corpus) # call the method .fit_transform( ) on the object tfidf_vectorizer and pass corpus to the function
df = pd.DataFrame(X.toarray(), index=doc_names, columns=tfidf_vectorizer.get_feature_names())
# create the data frame
df

catches  cats   day   eat  every  fish  leo  once   the
Doc0      0.0  0.25  0.00  0.25    0.0  0.25  0.0  0.00  0.25
Doc1      0.2  0.00  0.20  0.00    0.2  0.20  0.2  0.00  0.00
Doc2      0.0  0.00  0.25  0.25    0.0  0.25  0.0  0.25  0.00