In [3]:
import pandas as pd #Pandas library
import numpy as np # NumPy library
import sklearn
from sklearn.feature_extraction.text import TfidfTransformer
#from the module sklearn.feature_extraction.text import the class TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
#from the module sklearn.feature_extraction.text import the class CountVectorizer

In [1]:
corpus = ['The cats eat fish',
'Leo catches fish every day',
'Once a day I eat fish'
]

In [13]:
cv=CountVectorizer() #create the object cv to create an instance of the class CountVectorizer
word_count_vector=cv.fit_transform(corpus) # calculate word counts in corpus using the .fit_transform ( ) method
tokens = cv.get_feature_names() #return a list of feature names sorted by their indices using .get_feature_names_out ( ) method

In [14]:
print(word_count_vector.shape) #print the shape of the matrix (rows and columns)
print(tokens)
print(len(tokens))
print(word_count_vector.toarray()) #return an array method .toarray( )

(3, 9)
['catches', 'cats', 'day', 'eat', 'every', 'fish', 'leo', 'once', 'the']
9
[[0 1 0 1 0 1 0 0 1]
 [1 0 1 0 1 1 1 0 0]
 [0 0 1 1 0 1 0 1 0]]
